//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika_1_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchService
    {
        public int churchServiceID { get; set; }
        public System.DateTime service_date { get; set; }
        public Nullable<int> priest_id { get; set; }
        public Nullable<int> church_id { get; set; }
    
        public virtual Church Church {private get; set; }
        public virtual Priest Priest {private get; set; }
    }
}
